#include "config.h"
/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: qpb/qpb.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "qpb/qpb.pb-c.h"
void   qpb__ipv4_address__init
                     (Qpb__Ipv4Address         *message)
{
  static const Qpb__Ipv4Address init_value = QPB__IPV4_ADDRESS__INIT;
  *message = init_value;
}
size_t qpb__ipv4_address__get_packed_size
                     (const Qpb__Ipv4Address *message)
{
  assert(message->base.descriptor == &qpb__ipv4_address__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t qpb__ipv4_address__pack
                     (const Qpb__Ipv4Address *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &qpb__ipv4_address__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t qpb__ipv4_address__pack_to_buffer
                     (const Qpb__Ipv4Address *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &qpb__ipv4_address__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Qpb__Ipv4Address *
       qpb__ipv4_address__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Qpb__Ipv4Address *)
     protobuf_c_message_unpack (&qpb__ipv4_address__descriptor,
                                allocator, len, data);
}
void   qpb__ipv4_address__free_unpacked
                     (Qpb__Ipv4Address *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &qpb__ipv4_address__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   qpb__ipv6_address__init
                     (Qpb__Ipv6Address         *message)
{
  static const Qpb__Ipv6Address init_value = QPB__IPV6_ADDRESS__INIT;
  *message = init_value;
}
size_t qpb__ipv6_address__get_packed_size
                     (const Qpb__Ipv6Address *message)
{
  assert(message->base.descriptor == &qpb__ipv6_address__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t qpb__ipv6_address__pack
                     (const Qpb__Ipv6Address *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &qpb__ipv6_address__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t qpb__ipv6_address__pack_to_buffer
                     (const Qpb__Ipv6Address *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &qpb__ipv6_address__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Qpb__Ipv6Address *
       qpb__ipv6_address__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Qpb__Ipv6Address *)
     protobuf_c_message_unpack (&qpb__ipv6_address__descriptor,
                                allocator, len, data);
}
void   qpb__ipv6_address__free_unpacked
                     (Qpb__Ipv6Address *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &qpb__ipv6_address__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   qpb__l3_address__init
                     (Qpb__L3Address         *message)
{
  static const Qpb__L3Address init_value = QPB__L3_ADDRESS__INIT;
  *message = init_value;
}
size_t qpb__l3_address__get_packed_size
                     (const Qpb__L3Address *message)
{
  assert(message->base.descriptor == &qpb__l3_address__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t qpb__l3_address__pack
                     (const Qpb__L3Address *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &qpb__l3_address__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t qpb__l3_address__pack_to_buffer
                     (const Qpb__L3Address *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &qpb__l3_address__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Qpb__L3Address *
       qpb__l3_address__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Qpb__L3Address *)
     protobuf_c_message_unpack (&qpb__l3_address__descriptor,
                                allocator, len, data);
}
void   qpb__l3_address__free_unpacked
                     (Qpb__L3Address *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &qpb__l3_address__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   qpb__l3_prefix__init
                     (Qpb__L3Prefix         *message)
{
  static const Qpb__L3Prefix init_value = QPB__L3_PREFIX__INIT;
  *message = init_value;
}
size_t qpb__l3_prefix__get_packed_size
                     (const Qpb__L3Prefix *message)
{
  assert(message->base.descriptor == &qpb__l3_prefix__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t qpb__l3_prefix__pack
                     (const Qpb__L3Prefix *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &qpb__l3_prefix__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t qpb__l3_prefix__pack_to_buffer
                     (const Qpb__L3Prefix *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &qpb__l3_prefix__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Qpb__L3Prefix *
       qpb__l3_prefix__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Qpb__L3Prefix *)
     protobuf_c_message_unpack (&qpb__l3_prefix__descriptor,
                                allocator, len, data);
}
void   qpb__l3_prefix__free_unpacked
                     (Qpb__L3Prefix *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &qpb__l3_prefix__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   qpb__if_identifier__init
                     (Qpb__IfIdentifier         *message)
{
  static const Qpb__IfIdentifier init_value = QPB__IF_IDENTIFIER__INIT;
  *message = init_value;
}
size_t qpb__if_identifier__get_packed_size
                     (const Qpb__IfIdentifier *message)
{
  assert(message->base.descriptor == &qpb__if_identifier__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t qpb__if_identifier__pack
                     (const Qpb__IfIdentifier *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &qpb__if_identifier__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t qpb__if_identifier__pack_to_buffer
                     (const Qpb__IfIdentifier *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &qpb__if_identifier__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Qpb__IfIdentifier *
       qpb__if_identifier__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Qpb__IfIdentifier *)
     protobuf_c_message_unpack (&qpb__if_identifier__descriptor,
                                allocator, len, data);
}
void   qpb__if_identifier__free_unpacked
                     (Qpb__IfIdentifier *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &qpb__if_identifier__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor qpb__ipv4_address__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Qpb__Ipv4Address, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned qpb__ipv4_address__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange qpb__ipv4_address__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor qpb__ipv4_address__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "qpb.Ipv4Address",
  "Ipv4Address",
  "Qpb__Ipv4Address",
  "qpb",
  sizeof(Qpb__Ipv4Address),
  1,
  qpb__ipv4_address__field_descriptors,
  qpb__ipv4_address__field_indices_by_name,
  1,  qpb__ipv4_address__number_ranges,
  (ProtobufCMessageInit) qpb__ipv4_address__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor qpb__ipv6_address__field_descriptors[1] =
{
  {
    "bytes",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Qpb__Ipv6Address, bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned qpb__ipv6_address__field_indices_by_name[] = {
  0,   /* field[0] = bytes */
};
static const ProtobufCIntRange qpb__ipv6_address__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor qpb__ipv6_address__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "qpb.Ipv6Address",
  "Ipv6Address",
  "Qpb__Ipv6Address",
  "qpb",
  sizeof(Qpb__Ipv6Address),
  1,
  qpb__ipv6_address__field_descriptors,
  qpb__ipv6_address__field_indices_by_name,
  1,  qpb__ipv6_address__number_ranges,
  (ProtobufCMessageInit) qpb__ipv6_address__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor qpb__l3_address__field_descriptors[2] =
{
  {
    "v4",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Qpb__L3Address, v4),
    &qpb__ipv4_address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v6",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Qpb__L3Address, v6),
    &qpb__ipv6_address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned qpb__l3_address__field_indices_by_name[] = {
  0,   /* field[0] = v4 */
  1,   /* field[1] = v6 */
};
static const ProtobufCIntRange qpb__l3_address__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor qpb__l3_address__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "qpb.L3Address",
  "L3Address",
  "Qpb__L3Address",
  "qpb",
  sizeof(Qpb__L3Address),
  2,
  qpb__l3_address__field_descriptors,
  qpb__l3_address__field_indices_by_name,
  1,  qpb__l3_address__number_ranges,
  (ProtobufCMessageInit) qpb__l3_address__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor qpb__l3_prefix__field_descriptors[2] =
{
  {
    "length",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Qpb__L3Prefix, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bytes",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Qpb__L3Prefix, bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned qpb__l3_prefix__field_indices_by_name[] = {
  1,   /* field[1] = bytes */
  0,   /* field[0] = length */
};
static const ProtobufCIntRange qpb__l3_prefix__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor qpb__l3_prefix__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "qpb.L3Prefix",
  "L3Prefix",
  "Qpb__L3Prefix",
  "qpb",
  sizeof(Qpb__L3Prefix),
  2,
  qpb__l3_prefix__field_descriptors,
  qpb__l3_prefix__field_indices_by_name,
  1,  qpb__l3_prefix__number_ranges,
  (ProtobufCMessageInit) qpb__l3_prefix__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor qpb__if_identifier__field_descriptors[2] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Qpb__IfIdentifier, has_index),
    offsetof(Qpb__IfIdentifier, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Qpb__IfIdentifier, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned qpb__if_identifier__field_indices_by_name[] = {
  0,   /* field[0] = index */
  1,   /* field[1] = name */
};
static const ProtobufCIntRange qpb__if_identifier__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor qpb__if_identifier__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "qpb.IfIdentifier",
  "IfIdentifier",
  "Qpb__IfIdentifier",
  "qpb",
  sizeof(Qpb__IfIdentifier),
  2,
  qpb__if_identifier__field_descriptors,
  qpb__if_identifier__field_indices_by_name,
  1,  qpb__if_identifier__number_ranges,
  (ProtobufCMessageInit) qpb__if_identifier__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue qpb__address_family__enum_values_by_number[3] =
{
  { "UNKNOWN_AF", "QPB__ADDRESS_FAMILY__UNKNOWN_AF", 0 },
  { "IPV4", "QPB__ADDRESS_FAMILY__IPV4", 1 },
  { "IPV6", "QPB__ADDRESS_FAMILY__IPV6", 2 },
};
static const ProtobufCIntRange qpb__address_family__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex qpb__address_family__enum_values_by_name[3] =
{
  { "IPV4", 1 },
  { "IPV6", 2 },
  { "UNKNOWN_AF", 0 },
};
const ProtobufCEnumDescriptor qpb__address_family__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "qpb.AddressFamily",
  "AddressFamily",
  "Qpb__AddressFamily",
  "qpb",
  3,
  qpb__address_family__enum_values_by_number,
  3,
  qpb__address_family__enum_values_by_name,
  1,
  qpb__address_family__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue qpb__sub_address_family__enum_values_by_number[3] =
{
  { "UNKNOWN_SAF", "QPB__SUB_ADDRESS_FAMILY__UNKNOWN_SAF", 0 },
  { "UNICAST", "QPB__SUB_ADDRESS_FAMILY__UNICAST", 1 },
  { "MULTICAST", "QPB__SUB_ADDRESS_FAMILY__MULTICAST", 2 },
};
static const ProtobufCIntRange qpb__sub_address_family__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex qpb__sub_address_family__enum_values_by_name[3] =
{
  { "MULTICAST", 2 },
  { "UNICAST", 1 },
  { "UNKNOWN_SAF", 0 },
};
const ProtobufCEnumDescriptor qpb__sub_address_family__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "qpb.SubAddressFamily",
  "SubAddressFamily",
  "Qpb__SubAddressFamily",
  "qpb",
  3,
  qpb__sub_address_family__enum_values_by_number,
  3,
  qpb__sub_address_family__enum_values_by_name,
  1,
  qpb__sub_address_family__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue qpb__protocol__enum_values_by_number[11] =
{
  { "UNKNOWN_PROTO", "QPB__PROTOCOL__UNKNOWN_PROTO", 0 },
  { "LOCAL", "QPB__PROTOCOL__LOCAL", 1 },
  { "CONNECTED", "QPB__PROTOCOL__CONNECTED", 2 },
  { "KERNEL", "QPB__PROTOCOL__KERNEL", 3 },
  { "STATIC", "QPB__PROTOCOL__STATIC", 4 },
  { "RIP", "QPB__PROTOCOL__RIP", 5 },
  { "RIPNG", "QPB__PROTOCOL__RIPNG", 6 },
  { "OSPF", "QPB__PROTOCOL__OSPF", 7 },
  { "ISIS", "QPB__PROTOCOL__ISIS", 8 },
  { "BGP", "QPB__PROTOCOL__BGP", 9 },
  { "OTHER", "QPB__PROTOCOL__OTHER", 10 },
};
static const ProtobufCIntRange qpb__protocol__value_ranges[] = {
{0, 0},{0, 11}
};
static const ProtobufCEnumValueIndex qpb__protocol__enum_values_by_name[11] =
{
  { "BGP", 9 },
  { "CONNECTED", 2 },
  { "ISIS", 8 },
  { "KERNEL", 3 },
  { "LOCAL", 1 },
  { "OSPF", 7 },
  { "OTHER", 10 },
  { "RIP", 5 },
  { "RIPNG", 6 },
  { "STATIC", 4 },
  { "UNKNOWN_PROTO", 0 },
};
const ProtobufCEnumDescriptor qpb__protocol__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "qpb.Protocol",
  "Protocol",
  "Qpb__Protocol",
  "qpb",
  11,
  qpb__protocol__enum_values_by_number,
  11,
  qpb__protocol__enum_values_by_name,
  1,
  qpb__protocol__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
